# Dockerfile.dev
FROM python:3.11-slim

WORKDIR /app
RUN pip install mlflow==2.13.1 google-cloud-storage prometheus-flask-exporter
COPY . .

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH="/app"

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install the package in editable mode
RUN pip install --no-cache-dir -e .

# Exposes the Flask port
EXPOSE 5000
