global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'churn-app'
    static_configs:
      - targets: ['churn-app:5000']
        
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']