#mlflow-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: mlflow
        image: gcr.io/serious-cat-455501-d2/mlflow-telco:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials.json"
        command:
        - sh
        - -c
        - |
          mlflow server \
            --backend-store-uri sqlite:////mlflow/mlflow.db \
            --default-artifact-root gs://my_bucket_custumer_churn \
            --host 0.0.0.0 \
            --port 5000
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow
        - name: gcp-secret
          mountPath: /app/credentials.json
          subPath: credentials.json
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5

      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
      - name: gcp-secret
        secret:
          secretName: gcp-key

