#model-training-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-mlflow
        image: busybox:1.35
        command:
          - sh
          - -c
          - |
            echo "Waiting for MLflow on port 5000..."
            until nc -z mlflow-service 5000; do
              echo "Ainda não responde, tentando em 5s"
              sleep 5
            done
            echo "mlflow-service ready!"
      containers:
      - name: trainer
        image: gcr.io/serious-cat-455501-d2/ml-telco-churn:latest
        command: ["python","-u","pipeline/training_pipeline.py"]
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials.json"
        volumeMounts:
        - name: gcp-secret
          mountPath: "/app/credentials.json"
          subPath: credentials.json
      volumes:
      - name: gcp-secret
        secret:
          secretName: gcp-key
