# k8s/model-training-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: gcr.io/serious-cat-455501-d2/ml-telco-churn:latest
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials.json"
        command: ["python", "pipeline/training_pipeline.py"]
        volumeMounts:
        - name: gcp-secret
          mountPath: "/app/credentials.json"
          subPath: "credentials.json"
      volumes:
      - name: gcp-secret
        secret:
          secretName: gcp-key
      restartPolicy: Never
  backoffLimit: 4