apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'churn-app'
        static_configs:
          - targets: ['churn-app.default.svc.cluster.local:5000']
