apiVersion: batch/v1
kind: Job
metadata:
  name: ml-training-job
spec:
  ttlSecondsAfterFinished: 3600 # Auto-delete após 1 hora
  template:
    spec:
      containers:
      - name: training-container
        image: gcr.io/serious-cat-455501-d2/ml-telco-churn:latest
        command: ["python", "-m", "pipeline/training_pipeline.py"]
        env:
          - name: DB_HOST
            value: "postgres-service" # Nome do serviço do PostgreSQL
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: DB_NAME
            value: "postgres"
      restartPolicy: Never
  backoffLimit: 1