db_config:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres

split_data_config:
  train_ratio : 0.8
  random_state: 42
  target: "Churn"

model_config:
  class_weight: "balanced"
  random_state: 42

grid_search_config:
  scoring: "f1"
  cv: 5
  n_jobs: -1
  verbose: 1
  param_grid:
    n_estimators: [100, 200, 400, 600]
    max_depth: [null, 10, 20, 40]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ["sqrt", "log2"]  